git-ifaddrs-linknamespace
commit 7edd06916d0f18714f323b180b890f1fea39e1ff
Author: H.J. Lu <hjl.tools@gmail.com>
Date:   Wed Sep 27 17:18:32 2017 -0700

    Update sysdeps/unix/sysv/linux/ifaddrs.c
    
    Fix
    
    ../sysdeps/unix/sysv/linux/ifaddrs.c:835:27: error: ‘getifaddrs’ aliased to undefined symbol ‘__getifaddrs’
     weak_alias (__getifaddrs, getifaddrs)
                               ^
    ../sysdeps/unix/sysv/linux/ifaddrs.c:844:28: error: ‘freeifaddrs’ aliased to undefined symbol ‘__freeifaddrs’
     weak_alias (__freeifaddrs, freeifaddrs)
    
    caused by
    
    commit 4009ddc69225d571772aaea597615a0c032e14ab
    Author: Samuel Thibault <samuel.thibault@ens-lyon.org>
    Date:   Thu Sep 28 00:19:18 2017 +0200
    
        hurd: Fix `getifaddrs' and `freeifaddrs' symbol exposition
    
            * sysdeps/unix/sysv/linux/ifaddrs.c (__getifaddrs): Add
            libc_hidden_def.
            (__freeifaddrs): Likewise.

commit 4009ddc69225d571772aaea597615a0c032e14ab
Author: Samuel Thibault <samuel.thibault@ens-lyon.org>
Date:   Thu Sep 28 00:19:18 2017 +0200

    hurd: Fix `getifaddrs' and `freeifaddrs' symbol exposition
    
    from `freeaddrinfo'.
    
    `getifaddrs' and `freeifaddrs' are not in POSIX, they should not be
    exposed along `freeaddrinfo' (through `__check_pf') which is POSIX.
    
            * include/ifaddrs.h (__getifaddrs, __freeifaddrs): New declarations,
            and use libc_hidden_def on them.
            * inet/ifaddrs.c (__getifaddrs, __freeifaddrs): Use libc_hidden_def on
            them.
            * sysdeps/gnu/ifaddrs.c (__getifaddrs, __freeifaddrs): Likewise.
            * inet/check_pf.c (__check_pf): Use __getifaddrs and __freeifaddrs
            instead of getifaddrs and freeifaddrs.


Gbp-Pq: Topic hurd-i386
Gbp-Pq: Name git-ifaddrs-linknamespace.diff